name: Keep Streamlit Apps Alive

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit Apps
        run: |
          curl -I https://aspectfilter.streamlit.app/
          curl -I https://stock-scanner-ascpect.streamlit.app/
          curl -I https://fnoreversalpnt.streamlit.app/
          curl -I https://optionchainbygaurav.streamlit.app/
          curl -I https://liveplanetpostion.streamlit.app/
          curl -I https://raosaab.streamlit.app/
          curl -I https://fiidii.streamlit.app/
          curl -I https://fnopricecycle.streamlit.app/
          curl -I https://ganncycle.streamlit.app/
          curl -I https://niftytimecycle.streamlit.app/
          curl -I https://intradayreversal.streamlit.app/
          curl -I https://allnews.streamlit.app/
          curl -I https://multis.streamlit.app/
          curl -I https://oiwithgsy.streamlit.app/
          curl -I https://oidecay.streamlit.app/
          curl -I https://suncycle.streamlit.app/
          curl -I https://usaweather.streamlit.app/
          curl -I https://usaweather1.streamlit.app/
          curl -I https://usweather2.streamlit.app/
