name: Keep Streamlit Apps Alive

on:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit Apps
        run: |
          curl -L https://aspectfilter.streamlit.app/
          curl -L https://stock-scanner-ascpect.streamlit.app/
          curl -L https://fnoreversalpnt.streamlit.app/
          curl -L https://optionchainbygaurav.streamlit.app/
          curl -L https://liveplanetpostion.streamlit.app/
          curl -L https://raosaab.streamlit.app/
          curl -L https://fiidii.streamlit.app/
          curl -L https://fnopricecycle.streamlit.app/
          curl -L https://ganncycle.streamlit.app/
          curl -L https://niftytimecycle.streamlit.app/
          curl -L https://intradayreversal.streamlit.app/
          curl -L https://allnews.streamlit.app/
          curl -L https://multis.streamlit.app/
          curl -L https://oiwithgsy.streamlit.app/
          curl -L https://oidecay.streamlit.app/
          curl -L https://suncycle.streamlit.app/
          curl -L https://usaweather.streamlit.app/
          curl -L https://usaweather1.streamlit.app/
          curl -L https://usweather2.streamlit.app/
